### ISSUE TITLE
After following the installation instructions I get the following error

### ISSUE THREAD

**Issue by christianjoun** [almariah/k8s-metadata-injector#1]
`W0313 23:37:52.177907       1 client_config.go:549] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0313 23:37:52.185843       1 controller.go:99] Starting ebs-tagger controller
I0313 23:37:52.185903       1 controller.go:106] Waiting for informer caches to sync
I0313 23:37:52.386264       1 controller.go:114] Starting workers
I0313 23:37:52.386357       1 controller.go:120] Started workers
E0313 23:37:52.386514       1 runtime.go:69] Observed a panic: "index out of range" (runtime error: index out of range)
/Users/abdullah/go/src/k8s.io/apimachinery/pkg/util/runtime/runtime.go:76
/Users/abdullah/go/src/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/Users/abdullah/go/src/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/Cellar/go/1.11.4/libexec/src/runtime/asm_amd64.s:522
/usr/local/Cellar/go/1.11.4/libexec/src/runtime/panic.go:513
/usr/local/Cellar/go/1.11.4/libexec/src/runtime/panic.go:44
/Users/abdullah/Sandbox/kub/k8s-metadata-injector/controller.go:179
/Users/abdullah/Sandbox/kub/k8s-metadata-injector/controller.go:145
/Users/abdullah/Sandbox/kub/k8s-metadata-injector/controller.go:131
/Users/abdullah/Sandbox/kub/k8s-metadata-injector/controller.go:117
/Users/abdullah/go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:133
/Users/abdullah/go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:134
/Users/abdullah/go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/usr/local/Cellar/go/1.11.4/libexec/src/runtime/asm_amd64.s:1333
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 44 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/Users/abdullah/go/src/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x108
panic(0x13eaa40, 0x23af9b0)
	/usr/local/Cellar/go/1.11.4/libexec/src/runtime/panic.go:513 +0x1b9
main.(*Controller).process(0xc00026ff00, 0xc00048c074, 0x7, 0x15b47ce, 0x6, 0x0, 0x38)
	/Users/abdullah/Sandbox/kub/k8s-metadata-injector/controller.go:179 +0x5e2
main.(*Controller).processNext(0xc00026ff00, 0xc00033d400)
	/Users/abdullah/Sandbox/kub/k8s-metadata-injector/controller.go:145 +0xff
main.(*Controller).runWorker(0xc00026ff00)
	/Users/abdullah/Sandbox/kub/k8s-metadata-injector/controller.go:131 +0x2b
main.(*Controller).runWorker-fm()
	/Users/abdullah/Sandbox/kub/k8s-metadata-injector/controller.go:117 +0x2a
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000477b20)
	/Users/abdullah/go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000477b20, 0x3b9aca00, 0x0, 0x1, 0xc00007c660)
	/Users/abdullah/go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbe
k8s.io/apimachinery/pkg/util/wait.Until(0xc000477b20, 0x3b9aca00, 0xc00007c660)
	/Users/abdullah/go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by main.(*Controller).Run
	/Users/abdullah/Sandbox/kub/k8s-metadata-injector/controller.go:117 +0x343
`

**Comment by eedgar** [comment]
I am seeing this issue also.
